config/routes.rb
ZEmpower::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "culsertions/index"
  resources :articles
  resources :blogs
  resources :culsertions

  get "home/index"

  root 'home#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/culsertion.rb
class Culsertion < ActiveRecord::Base
end

app/models/news_article.rb
class NewsArticle < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # before_action :require_admin, except: [:index, :show]


  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :media, :published, :author, :posted_on, :teaser)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

 
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :teaser, :content, :media, :published, :author, :posted_on)
    end
end

app/controllers/culsertions_controller.rb
class CulsertionsController < ApplicationController
  before_action :set_culsertion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /culsertions
  # GET /culsertions.json
  def index
    @culsertions = Culsertion.all
  end

  # GET /culsertions/1
  # GET /culsertions/1.json
  def show
  end

  # GET /culsertions/new
  def new
    @culsertion = Culsertion.new
  end

  # GET /culsertions/1/edit
  def edit
  end

  # POST /culsertions
  # POST /culsertions.json
  def create
    @culsertion = Culsertion.new(culsertion_params)

    respond_to do |format|
      if @culsertion.save
        format.html { redirect_to @culsertion, notice: 'culsertion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @culsertion }
      else
        format.html { render action: 'new' }
        format.json { render json: @culsertion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /culsertions/1
  # PATCH/PUT /culsertions/1.json
  def update
    respond_to do |format|
      if @culsertion.update(culsertion_params)
        format.html { redirect_to @culsertion, notice: 'Culsertion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @culsertion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /culsertions/1
  # DELETE /culsertions/1.json
  def destroy
    @culsertion.destroy
    respond_to do |format|
      format.html { redirect_to culsertions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_culsertion
      @culsertion = Culsertion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def culsertion_params
      params.require(:culsertion).permit(:title, :content, :tally)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/culsertions_helper.rb
module CulsertionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>    
    <%= f.text_field :title %><br><br>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %><br><br>
  </div>
  <div class="field">
    <%= f.label :teaser %>
    <%= f.text_area :teaser %><br><br>
  </div>
  <div class="field">
    <%= f.label :media %>
    <%= f.text_field :media %><br><br>
  </div>
  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %><br><br>
  </div>
  <div class="field">
    <%= f.label :posted_on %>
    <%= f.date_select :posted_on %><br><br>
  </div>
  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1><br>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Latest News:</h1>


<% @articles.each do |article| %>
  <div class='article_display'>
    <h2><%= link_to article.title, article_path(article) %></h2>
      <%= article.media %>
    <p><%= article.teaser %></p>
    <em class="author">By <%= article.author %></em><br>
    <span class='published_on'>Published on <%= article.posted_on %></span>
  </div>    
<% end %>
  <%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @article.title %></h1>
  Posted on: <%= @article.posted_on %>
<p>
  image can go here
</p>
<div class="article_content">
  <%=raw @article.content %>
</div>
<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<%= link_to 'Back', articles_path %>
|   <%= link_to 'New Article', new_article_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>
| <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :teaser %><br>
    <%= f.text_area :teaser %>
  </div>
  <div class="field">
    <%= f.label :media %><br>
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :posted_on %><br>
    <%= f.date_select :posted_on %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
   <div class="row blog_index_section">   


      <h1>Blog Posts:</h1>



<% @blogs.each do |blog| %>
  <div class='blog_display'>
    <h2><%= link_to blog.title, blog_path(blog) %></h2>
      <%= blog.media %>
    <p><%=raw blog.teaser %></p>
    <em class="author">By <%= blog.author %></em><br>
    <span class='published_on'>Published on <%= blog.posted_on %></span>
  </div>    
<% end %>
  <%= link_to 'New Blog', new_blog_path %>

</div>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @blog.title %></h1>
  Posted on: <%= @blog.posted_on %>
<p>
  <!-- image can go here -->
</p>

<div class="blog_content">
  <%=raw @blog.content %>
</div>
<br>
<br>
<br>
<p>
  <strong>Author:</strong>
  <%= @blog.author %>
</p>


<%= link_to 'Back', blogs_path %>
| <%= link_to 'New Blog', new_blog_path %>
| <%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
| <%= link_to 'Edit', edit_blog_path(@blog) %> 

app/views/culsertions/_form.html.erb
<%= form_for(@culsertion) do |f| %>
  <% if @culsertion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@culsertion.errors.count, "error") %> prohibited this culsertion from being saved:</h2>

      <ul>
      <% @culsertion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/culsertions/edit.html.erb
<h1>Editing culsertion</h1>

<%= render 'form' %>

<%= link_to 'Show', @culsertion %> |
<%= link_to 'Back', culsertions_path %>

app/views/culsertions/index.html.erb
<h1>Cultural Assertions:</h1>


<% @culsertions.each do |culsertion| %>
  <div class='culsertion_display'>
    <h2><%= link_to culsertion.title, culsertion_path(culsertion) %></h2>
    <p><%= culsertion.content %></p>
  </div>    
<% end %>
  <%= link_to 'New culsertion', new_culsertion_path %>

app/views/culsertions/new.html.erb
<h1>New Culsertion</h1>

<%= render 'form' %>

<%= link_to 'Back', culsertions_path %>

app/views/culsertions/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @culsertion.title %></h1>
 

<div class="culsertion_content">
  <%= @culsertion.content %>
</div>


 <%= link_to 'Back', culsertions_path %>
|<%= link_to 'New', new_culsertion_path %>
| <%= link_to 'Destroy', @culsertion, method: :delete, data: { confirm: 'Are you sure?' } %>
| <%= link_to 'Edit', edit_culsertion_path(@culsertion) %> 

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<!-- <iframe width="420" height="315" src="//www.youtube.com/embed/<%#= my_video_id_here %>" frameborder="0" allowfullscreen></iframe> -->
<iframe width="420" height="315" src="//www.youtube.com/embed/NTHBC6JOc4M" frameborder="0" allowfullscreen></iframe>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <li><%#= link_to 'About', page_path('about') %></li>
  <li><%= link_to 'News', articles_path %></li>
  <li><%= link_to 'Blog', blogs_path %></li>
  <li><%= link_to 'Vote', culsertions_path %></li>
   <li><%= link_to 'Admin', admin_root_path %></li>
  <li>
    <a href="#">   <%=  image_tag("twitter.png")  %></a>

     <!-- <img alt="Twitter" height="34" src="/assets/icons/twitter.png" width="34" /> -->
      <!-- <span class="name">follow on Twitter</span> -->

  </li>
  <li>  <a href="#">   <%=  image_tag("facebook.png", height: "34", class: "facebook")  %></a>
   
    <!-- <span class="name">follow on Facebook</span> -->
  </li>
</ul>
     <div class="pull-right">
        <%# if logged_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn' %>
        <%# else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-success' %>
        <%# end %>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
<!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
<![endif]-->

  

  </head>
  <body class="gradient">

<!--  <header class="navbar navbar-fixed-top"> -->
    <header class="navbar ">

      <div class="banner row"> 

        <div class="span7">
        <h1 id="main-title">Design Your Society</h1>
       <h4 id="subtitle">So the little guy can win!</h4>
         
        </div>
 <%#= image_tag("winning_crowd.png", height: '100')  %>

        <!-- <div class="span4 offset1"></div> -->
      <!-- </div> -->
       

      </div>
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>



    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>